"""Add completed field to saving_goals

Revision ID: 5138fefaa70f
Revises: e2c27b1558bd
Create Date: 2026-02-13 21:03:02.564511

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5138fefaa70f'
down_revision = 'e2c27b1558bd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('investments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('starting_capital', sa.Float(), nullable=False))

    with op.batch_alter_table('saving_goals', schema=None) as batch_op:
        batch_op.add_column(sa.Column('completed', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('saving_goals', schema=None) as batch_op:
        batch_op.drop_column('completed')

    with op.batch_alter_table('investments', schema=None) as batch_op:
        batch_op.drop_column('starting_capital')

    # ### end Alembic commands ###
