"""Corrigindo relacionamento entre User e Account

Revision ID: e2c27b1558bd
Revises: 
Create Date: 2026-02-08 05:54:22.117865

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e2c27b1558bd'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('account', schema=None) as batch_op:
        batch_op.alter_column('account_name',
                              existing_type=sa.VARCHAR(length=100),
                              type_=sa.String(length=255),
                              existing_nullable=False)
        batch_op.drop_column('account_balance')

    with op.batch_alter_table('expense', schema=None) as batch_op:
        batch_op.alter_column('description',
                              existing_type=sa.VARCHAR(length=200),
                              type_=sa.String(length=255),
                              nullable=False)
        batch_op.alter_column('expense_date',
                              existing_type=sa.DATETIME(),
                              type_=sa.Date(),
                              nullable=False)

    with op.batch_alter_table('transaction_type', schema=None) as batch_op:
        batch_op.alter_column('name',
                              existing_type=sa.VARCHAR(length=50),
                              type_=sa.String(length=255),
                              existing_nullable=False)
        batch_op.alter_column('transaction_category',
                              existing_type=sa.VARCHAR(length=20),
                              type_=sa.String(length=50),
                              existing_nullable=False)
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('user_id')

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('fullname',
                              existing_type=sa.VARCHAR(length=150),
                              type_=sa.String(length=255),
                              existing_nullable=False)
        batch_op.alter_column('email',
                              existing_type=sa.VARCHAR(length=150),
                              type_=sa.String(length=255),
                              existing_nullable=False)
        batch_op.alter_column('password',
                              existing_type=sa.VARCHAR(length=150),
                              type_=sa.String(length=255),
                              existing_nullable=False)
        batch_op.drop_column('username')
        batch_op.drop_column('create_at')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column('create_at', sa.DATETIME(), nullable=True))
        batch_op.add_column(
            sa.Column('username', sa.VARCHAR(length=150), nullable=False))
        batch_op.alter_column('password',
                              existing_type=sa.String(length=255),
                              type_=sa.VARCHAR(length=150),
                              existing_nullable=False)
        batch_op.alter_column('email',
                              existing_type=sa.String(length=255),
                              type_=sa.VARCHAR(length=150),
                              existing_nullable=False)
        batch_op.alter_column('fullname',
                              existing_type=sa.String(length=255),
                              type_=sa.VARCHAR(length=150),
                              existing_nullable=False)

    with op.batch_alter_table('transaction_type', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.INTEGER(), nullable=False))
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'])
        batch_op.alter_column('transaction_category',
                              existing_type=sa.String(length=50),
                              type_=sa.VARCHAR(length=20),
                              existing_nullable=False)
        batch_op.alter_column('name',
                              existing_type=sa.String(length=255),
                              type_=sa.VARCHAR(length=50),
                              existing_nullable=False)

    with op.batch_alter_table('expense', schema=None) as batch_op:
        batch_op.alter_column('expense_date',
                              existing_type=sa.Date(),
                              type_=sa.DATETIME(),
                              nullable=True)
        batch_op.alter_column('description',
                              existing_type=sa.String(length=255),
                              type_=sa.VARCHAR(length=200),
                              nullable=True)

    with op.batch_alter_table('account', schema=None) as batch_op:
        batch_op.add_column(sa.Column('account_balance',
                            sa.FLOAT(), nullable=False))
        batch_op.alter_column('account_name',
                              existing_type=sa.String(length=255),
                              type_=sa.VARCHAR(length=100),
                              existing_nullable=False)

    # ### end Alembic commands ###
